# Site settings
title: Notes | Hwei's Academic notes.
#description: "A minimal, responsive, ready to use blog template, built with Jekyll."
url: "https://hwei-esay.github.io/"
#author:
#  name: "The Review Index"
#  email: "dyutibarma@gmail.com"
#  url: "https://thereviewindex.com"

# Build settings
baseurl: /notes # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

usemathjax: true

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
